[[main]]
  name = "Main"
  pageRef = "/"
  weight = 10

[[main]]
  name = "Units"
  pageRef = "units"
  weight = 20

[[main]]
  name = "Posts"
  pageRef = "posts"
  weight = 30

[[main]]
  name = "Tags"
  parent = "Posts"
  pageRef = "tags"
  weight = 20

[[main]]
  name = "Authors"
  parent = "Posts"
  pageRef = "authors"
  weight = 30

#[[subnavigation]]
#  name = "An interesting topic"
#  pageRef = "tags/interesting-topic"
#  weight = 10

# -- Footer Menu --
# The footer menu is displayed at the bottom of the page, just before
# the copyright notice. Configure as per the main menu above.

[[footer]]
  name = "RSS"
  pre = "rss"
  url = "/index.xml"
  weight = 10

[[footer]]
  pre = "github"
  name = "GitHub"
  url = "https://github.com/The-Alium"
  weight = 20

[[footer]]
  pre = "steam"
  name = "Steam"
  url = "https://steamcommunity.com/groups/thealium"
  weight = 30

[[footer]]
  pre = "discord"
  name = "Discord"
  url = "https://discord.gg/BmQSQEm8GW"
  weight = 40

[[footer]]
  pre = "youtube"
  name = "YouTube"
  url = "https://www.youtube.com/@aliumculture"
  weight = 50
